import { readFile, writeFile } from "node:fs/promises";
import { isAbsolute, resolve } from "node:path";
import { CUTROOM_VERSION } from "../schema.js";
import {
  contentInventoryPath,
  editPlanPath,
  storyCandidatesPath,
  storySelectionPath,
} from "../project.js";
import { ensureDir, writeJson } from "../files.js";
import { HANIF_CONTENT_PROFILE } from "./profiles/hanif.js";
import {
  TALKING_HEAD_STORY_RECIPE,
  buildTalkingHeadStoryPackage,
} from "./recipes/talking-head-story.js";
import {
  ContentProfileSchema,
  StoryCandidatesSchema,
  type BuildContentPackageOptions,
  type ContentPackage,
  type ContentProfile,
  type ContentRecipe,
  type ResolvedContentPackageOptions,
  type StoryCandidates,
  type WriteContentPackageOptions,
} from "./schema.js";

export {
  HANIF_CONTENT_PROFILE,
  TALKING_HEAD_STORY_RECIPE,
  ContentProfileSchema,
  StoryCandidatesSchema,
};
export type {
  BuildContentPackageOptions,
  ContentPackage,
  ContentProfile,
  ContentRecipe,
  StoryCandidate,
  StoryCandidates,
  SuggestedArtifact,
  WriteContentPackageOptions,
} from "./schema.js";

const BUILT_IN_PROFILES = new Map<string, ContentProfile>([
  [HANIF_CONTENT_PROFILE.id, HANIF_CONTENT_PROFILE],
]);

const BUILT_IN_RECIPES = new Map<string, ContentRecipe>([
  [TALKING_HEAD_STORY_RECIPE.id, TALKING_HEAD_STORY_RECIPE],
]);

export function getBuiltInProfile(id: string): ContentProfile | null {
  return BUILT_IN_PROFILES.get(id) ?? null;
}

export function getBuiltInRecipe(id: string): ContentRecipe | null {
  return BUILT_IN_RECIPES.get(id) ?? null;
}

export async function loadContentProfile(idOrPath: string): Promise<ContentProfile> {
  const builtIn = getBuiltInProfile(idOrPath);
  if (builtIn) return builtIn;
  const path = isAbsolute(idOrPath) ? idOrPath : resolve(idOrPath);
  const raw = await readFile(path, "utf8").catch((error: unknown) => {
    throw new Error(
      `Unknown content profile '${idOrPath}'. Use a built-in id or a JSON profile path. ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  });
  return ContentProfileSchema.parse(JSON.parse(raw));
}

export function loadContentRecipe(id: string): ContentRecipe {
  const builtIn = getBuiltInRecipe(id);
  if (builtIn) return builtIn;
  throw new Error(`Unknown content recipe '${id}'. Built-in recipes: ${[...BUILT_IN_RECIPES.keys()].join(", ")}`);
}

function resolveOptions(options: BuildContentPackageOptions): ResolvedContentPackageOptions {
  const defaults = options.profile.defaults;
  return {
    ...options,
    targetDurationMs: Math.max(1000, Math.round(options.targetDurationMs ?? defaults.targetDurationMs)),
    minDurationMs: Math.max(1000, Math.round(options.minDurationMs ?? defaults.minDurationMs)),
    maxDurationMs: Math.max(1000, Math.round(options.maxDurationMs ?? defaults.maxDurationMs)),
    maxCandidates: Math.max(1, Math.round(options.maxCandidates ?? defaults.maxCandidates)),
    leadPaddingMs: Math.max(0, Math.round(options.leadPaddingMs ?? defaults.leadPaddingMs)),
    tailPaddingMs: Math.max(0, Math.round(options.tailPaddingMs ?? defaults.tailPaddingMs)),
  };
}

export function buildContentPackage(options: BuildContentPackageOptions): ContentPackage {
  const resolved = resolveOptions(options);
  switch (resolved.recipe.id) {
    case TALKING_HEAD_STORY_RECIPE.id:
      return buildTalkingHeadStoryPackage(resolved);
    default:
      throw new Error(`Unsupported content recipe '${resolved.recipe.id}'.`);
  }
}

export async function writeContentPackage(options: WriteContentPackageOptions): Promise<ContentPackage> {
  const built = buildContentPackage(options);
  await ensureDir(resolve(options.projectDir, "review"));
  await ensureDir(resolve(options.projectDir, "analysis"));
  await writeJson(storyCandidatesPath(options.projectDir), built.storyCandidates);
  await writeFile(contentInventoryPath(options.projectDir), built.inventoryMarkdown);
  await writeFile(storySelectionPath(options.projectDir), built.selectionMarkdown);
  await writeJson(
    editPlanPath(options.projectDir),
    built.editPlan ?? {
      version: CUTROOM_VERSION,
      createdAt: new Date().toISOString(),
      sourcePath: options.sourcePath,
      segments: [],
      notes: [
        `Generated by content-package recipe ${options.recipe.id} with profile ${options.profile.id}.`,
        "No story candidate was selected; this edit plan intentionally has no renderable segments.",
      ],
    },
  );
  return built;
}

export async function readStoryCandidates(projectDir: string): Promise<StoryCandidates | null> {
  const path = storyCandidatesPath(projectDir);
  let raw: string;
  try {
    raw = await readFile(path, "utf8");
  } catch (error: unknown) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return null;
    throw error;
  }
  try {
    return StoryCandidatesSchema.parse(JSON.parse(raw));
  } catch (error: unknown) {
    throw new Error(
      `Invalid story candidates artifact at ${path}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}
