import { ContentProfileSchema, type ContentProfile } from "../schema.js";

export const HANIF_CONTENT_PROFILE: ContentProfile = ContentProfileSchema.parse({
  id: "hanif",
  version: 1,
  label: "Hanif Talking-Head Content",
  inventoryTitle: "Hanif Content Inventory",
  weakThemeWarning: "Weak match to the selected content profile themes.",
  defaults: {
    objective:
      "Find source-backed talking-head moments for Hanif's consulting, content, software, and workflow goals.",
    targetDurationMs: 75_000,
    minDurationMs: 35_000,
    maxDurationMs: 125_000,
    maxCandidates: 8,
    leadPaddingMs: 800,
    tailPaddingMs: 1200,
  },
  themes: [
    {
      id: "consulting-focus",
      label: "Consulting Focus",
      keywords: [
        "consulting",
        "technical consultant",
        "paid media",
        "agency",
        "agencies",
        "icp",
        "client",
        "clients",
        "offer",
        "diagnose",
        "operations",
        "workflow automation",
        "custom software",
        "reporting",
      ],
      priority: 1.08,
    },
    {
      id: "codex-operating-system",
      label: "Codex Operating System",
      keywords: [
        "codex",
        "operating system",
        "chief of staff",
        "obsidian",
        "decision note",
        "decision notes",
        "things",
        "tasks",
        "task",
        "perplexity",
        "review artifacts",
        "html file",
        "markdown file",
      ],
      priority: 1.04,
    },
    {
      id: "raw-thinking-to-content",
      label: "Raw Thinking To Content",
      keywords: [
        "content",
        "video",
        "writing",
        "twitter",
        "linkedin",
        "instagram",
        "tiktok",
        "personal brand",
        "post",
        "posting",
        "publish",
        "published",
        "upload",
        "algorithm",
      ],
      priority: 1.11,
    },
    {
      id: "public-building-proof",
      label: "Public Building Proof",
      keywords: [
        "building",
        "software",
        "project",
        "projects",
        "people to try",
        "feedback",
        "share",
        "world",
        "audience",
        "missed opportunity",
        "actually do things",
      ],
      priority: 1.14,
    },
    {
      id: "speaking-confidence",
      label: "Speaking Confidence",
      keywords: [
        "talk",
        "talking",
        "speak",
        "speaking",
        "camera",
        "confidence",
        "confident",
        "shy",
        "reserved",
        "imposter",
        "voice",
        "ideas",
        "microphone",
        "tripod",
      ],
      priority: 0.96,
    },
    {
      id: "effectiveness-and-task-graph",
      label: "Effectiveness And Task Graph",
      keywords: [
        "effective",
        "effectiveness",
        "efficient",
        "efficiency",
        "prioritize",
        "priority",
        "dag",
        "directed acyclic graph",
        "depends",
        "motivation",
        "decision paralysis",
        "to-do list",
        "today list",
      ],
      priority: 0.94,
    },
  ],
  openingSignalPatterns: [
    "the difference",
    "the interesting part",
    "important thing",
    "huge mistake",
    "missed opportunity",
    "i realized",
    "i decided",
    "i don't want",
    "i knew",
    "the first",
    "specific",
    "specificity",
    "the name of the game",
    "it just doesn't work",
    "you don't have to",
    "you need",
    "you can't",
    "now i feel",
    "this realization",
  ],
  fillerPatterns: ["kind of", "sort of", "i guess", "like", "um", "uh"],
  outcomeSignalPatterns: [
    "because",
    "so that",
    "as a result",
    "that's why",
    "that is why",
    "the result",
    "it helps",
    "you can",
    "you need",
    "the transformation",
    "what this means",
  ],
  listenerValueSignalPatterns: [
    "you need",
    "you can't",
    "people don't",
    "who is this for",
    "what does it do",
    "why would i want this",
    "the transformation",
    "better to do one thing",
    "specificity is the name of the game",
  ],
  personalDetailPatterns: [
    "so i got",
    "i got specific",
    "i did that today",
    "before this recording",
    "i was looking at",
    "my consulting",
    "my understanding of my icp",
    "i need to understand",
    "creating a kind of curriculum",
  ],
  transcriptReplacements: [
    { match: "\\binteracting with codecs\\b", replacement: "interacting with Codex" },
    { match: "\\bcloud code\\b", replacement: "Claude Code" },
    { match: "\\bchat\\s*gpt\\b", replacement: "ChatGPT" },
    { match: "\\bI the time\\b", replacement: "I dedicate the time", flags: "g" },
    { match: "\\b(\\w{3,})\\s+\\1\\b", replacement: "$1" },
  ],
  exactBoosts: [
    { allPhrases: ["actually do things", "never published"], boost: 0.16 },
    { allPhrases: ["specificity is the name of the game"], boost: 0.1 },
    { allPhrases: ["interacting with ai", "writing that i can publish"], boost: 0.08 },
    { allPhrases: ["codex", "chief of staff"], boost: 0.06 },
  ],
});
